name: C/C++ CI

on:
#  push:
#    branches: [ "v2.x" ]
#  pull_request:
#    branches: [ "v2.x" ]
#  schedule:
#    - cron: '15 13 * * 3'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install build tools
      run: sudo apt-get -y install make automake git wget gcc g++ libtool equivs python3 valgrind
      
    - name: Install build dependencies
      run: sudo apt-get -y install libssl-dev gnutls-dev libgnutls28-dev libmysqlclient-dev libboost-all-dev libunwind8 libunwind-dev uuid-dev ca-certificates
      
    - name: Install test tools
      run: sudo apt-get -y install mysql-client
            
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Git describe
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        export VERS=$(git ls-remote https://github.com/sysown/proxysql.git "refs/tags/*" | grep -v 'refs/tags/v' | sed -e 's|.*/||g' | tail -2 | head -1)
        export HASH=$(gh api repos/sysown/proxysql/git/refs/heads/v2.x | jq '.object.sha' | cut -c2-8)
        export CMTS=$(gh api repos/sysown/proxysql/compare/${VERS}...v2.x | jq '.ahead_by')
        echo "git descibe : ${VERS}-${CMTS}-g${HASH}"
        echo "GIT_VERSION=${VERS}-${CMTS}-g${HASH}" >> $GITHUB_ENV
    
    - name: Build
      run: |
        make debug_clickhouse
        
    - name: Self-tests
      run: |
        cd src && (./proxysql -f --initial --clickhouse --idle-threads -D . &>proxysql.log &)
        sleep 30
        mysql -uadmin -padmin -h127.0.0.1 -P6032 -e "SELECT 1;"
        echo 'DONE'

#        mysql -uadmin -padmin -h127.0.0.1 -P6032 -e "PROXYSQLTEST 1 1000;" 2>&1 | grep -v 'Using a password'
#        mysql -uadmin -padmin -h127.0.0.1 -P6032 -e "SELECT 1;" 2>&1 | grep -v 'Using a password'
        
        
