name: C/C++ CI

on:
#  push:
#    branches: [ "v2.x" ]
#  pull_request:
#    branches: [ "v2.x" ]
#  schedule:
#    - cron: '15 13 * * 3'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install build tools
      run: sudo apt-get -y install make automake git wget gcc g++ libtool equivs python3
      
    - name: Install build dependencies
      run: sudo apt-get -y install libssl-dev gnutls-dev libgnutls28-dev libmysqlclient-dev libboost-all-dev libunwind8 libunwind-dev uuid-dev ca-certificates
      
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Build C++
      run: |
        export VERS=$(git ls-remote https://github.com/sysown/proxysql.git "refs/tags/*" | grep -v 'refs/tags/v' | sed -e 's|.*/||g' | tail -2 | head -1)
        export HASH=$(gh api repos/sysown/proxysql/git/refs/heads/v2.x | jq '.object.sha' | cut -c2-8)
        export CMTS=$(gh api repos/sysown/proxysql/compare/${VERS}...v2.x | jq '.ahead_by')
        export GIT_VERSION=2.5.0-0-g0000000
        make clickhouse
        
