name: CI-3p-sqlalchemy

on:
#  push:
#    branches: [ "v2.x" ]
#    paths-ignore:
#    - '.github/**'
#    - '**.md'
#  pull_request:
#    branches: [ "v2.x" ]
#    paths-ignore:
#    - '.github/**'
#    - '**.md'
#  schedule:
#    - cron: '15 13 * * 3'
  workflow_dispatch:
  workflow_run:
    workflows: [ CI-builds ]
    types: [ completed ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  run-mysql:
    uses: mirostauder/proxysql/.github/workflows/ci-3p-sqlalchemy_mysql.yml@GH-Actions
    secrets: inherit
  run-mariadb:
    uses: mirostauder/proxysql/.github/workflows/ci-3p-sqlalchemy_mariadb.yml@GH-Actions
    secrets: inherit
    
