name: CI-3p-sqlalchemy

on:
  workflow_dispatch:
    inputs:
      p3pt_branch:
        default: main
        type: string
  workflow_run:
    workflows: [ CI-builds ]
    types: [ completed ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  run:
    uses: sysown/proxysql/.github/workflows/ci-3p-sqlalchemy.yml@GH-Actions
    secrets: inherit
    with:
      trigger: ${{ toJson(github) }}
      infradb: ${{ vars.MATRIX_3P_SQLALCHEMY_infradb_mariadb }}
      connector: ${{ vars.MATRIX_3P_SQLALCHEMY_connector_mariadb }}
