name: CI-basictests

on:
  workflow_dispatch:

  workflow_run:
    workflows: [ "CI-builds" ]
    types: [ completed ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  run:
    uses: mirostauder/proxysql/.github/workflows/ci-basictests.yml@GH-Actions
    with:
      ref: ${{ github.event.client_payload.ref }}
      sha: ${{ github.event.client_payload.sha }}
    secrets: inherit


    
