name: CI-builds
run-name: '${{ github.ref_name }} ${{ github.workflow }} ${{ github.sha }}'

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ CI-trigger ]
    types: [ completed ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  run:
    uses: mirostauder/proxysql/.github/workflows/ci-builds.yml@GH-Actions
    secrets: inherit
    
