name: CI-builds

on:
  push:
    branches: [ "v2.x" ]
    paths-ignore:
    - '.github/**'
    - '**.md'
  pull_request:
    branches: [ "v2.x" ]
    paths-ignore:
    - '.github/**'
    - '**.md'
#  schedule:
#    - cron: '15 13 * * 3'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}

env:
  REPO: ${{ github.repository }}

jobs:
  run:
    uses: ${{ env.REPO }}/.github/workflows/ci-builds.yml@GH-Actions
    secrets: inherit
    
