name: CI-builds

on:
  push:
#    branches: [ "v2.x" ]
    paths-ignore:
    - '.github/**'
    - '**.md'
    if: ""
  pull_request:
#    branches: [ "v2.x" ]
    paths-ignore:
    - '.github/**'
    - '**.md'
    if: startsWith(github.event.repository.default_branch, github.ref_name)
#  schedule:
#    - cron: '15 13 * * 3'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  run:
    uses: mirostauder/proxysql/.github/workflows/ci-builds.yml@GH-Actions
    secrets: inherit
    
