name: CI-dump
run-name: '${{ github.event.workflow_run && github.event.workflow_run.head_branch || github.ref_name }} ${{ github.workflow }} ${{ github.event.workflow_run && github.event.workflow_run.head_sha || github.sha }}'

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ CI-trigger ]
    types: [ completed ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run && github.event.workflow_run.head_branch || github.ref_name }}
  cancel-in-progress: true

jobs:
  run-dump:
    if: ${{ github.event.workflow_run && github.event.workflow_run.conclusion == 'success' || ! github.event.workflow_run }}
    uses: mirostauder/proxysql/.github/workflows/ci-dump.yml@GH-Actions
    secrets: inherit
    with:
#      sha: ${{ github.event.workflow_run.head_sha }}
      trigger: ${{ toJson(github) }}
#      infradb: "[ 'mysql57', 'mysql80', 'mysql84', 'mysql90' ]"
      infradb: ${{ vars.MATRIX_3P_SQLALCHEMY_infradb_mysql }}
#      connector: "[ 'pymysql', 'mysqldb', 'asyncmy', 'mariadbconnector' ]"
      connector: ${{ vars.MATRIX_3P_SQLALCHEMY_connector_mysql }}
    
