name: CI-dump

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ CI-builds ]
    types: [ completed ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  run-mysql:
    uses: mirostauder/proxysql/.github/workflows/ci-dump.yml@GH-Actions
    secrets: inherit
    with:
#      sha: ${{ github.event.workflow_run.head_sha }}
      trigger: ${{ toJson(github) }}
#      infradb: "[ 'mysql57', 'mysql80', 'mysql84', 'mysql90' ]"
      infradb: ${{ vars.CI_3P_SQLALCHEMY_infradb_mysql }}
      connector: "[ 'pymysql', 'mysqldb', 'asyncmy', 'mariadbconnector' ]"
    
