
name: CI-dump

on:
  workflow_dispatch:
  workflow_call:
    inputs:
#      sha:
#        type: string
      trigger:
        type: string
      infradb:
        type: string
      connector:
        type: string

permissions: write-all

env:
  SHA: ${{ fromJson(inputs.trigger).event.workflow_run.head_sha }}

jobs:
  items:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        infradb: ${{ fromJson(inputs.infradb) }}
        connector: ${{ fromJson(inputs.connector) }}
    
    steps:
    - name: Print Matrix Item
      run: |
        #echo ">>> ${{ inputs.sha }} ${{ matrix.infradb }} ${{ matrix.connector }} <<<"
        echo ">>> $SHA ${{ env.SHA }} ${{ matrix.infradb }} ${{ matrix.connector }} <<<"
    
    - uses: LouisBrunner/checks-action@v2.0.0
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ github.workflow }}
        repo: ${{ github.repo }}
        sha: ${{ env.SHA }}
        status: 'in_progress'
        action_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
        details_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'

    - name: Sleep
      run: |
        sleep 30

    - uses: LouisBrunner/checks-action@v2.0.0
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ github.workflow }}
        repo: ${{ github.repo }}
        sha: ${{ env.SHA }}
        conclusion: ${{ job.status }}
        action_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
        details_url: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'


  dump:
    runs-on: ubuntu-22.04
    steps:

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "${{ toJson(github) }}"

    - name: Dump Inputs context
      env:
        INPUTS_CONTEXT: ${{ toJson(inputs) }}
      run: echo "${{ toJson(inputs) }}"

    - name: Dump Secrets context
      env:
        SECRETS_CONTEXT: ${{ toJson(secrets) }}
      run: echo "$SECRETS_CONTEXT"

    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
      
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
      
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
      
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
      
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"
