name: CI-trigger
run-name: '${{ github.ref_name }} ${{ github.workflow }} ${{ github.sha }}'

on:
  push:
#    branches: [ 'v[0-9]+.x','v[0-9]+.[0-9]+','v[0-9]+.[0-9]+.[0-9]+' ]
    paths-ignore:
    - '.github/**'
    - '**.md'
#  schedule:
#    - cron: '15 13 * * 3'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  trigger:
    runs-on: ubuntu-22.04
