name: CI-trigger
run-name: '${{ github.ref_name }} ${{ github.workflow }} ${{ github.sha }}'

on:
  push:
#    branches: [ 'v[0-9]+.x','v[0-9]+.[0-9]+','v[0-9]+.[0-9]+.[0-9]+' ]
    paths-ignore:
    - '.github/**'
    - '**.md'
#  schedule:
#    - cron: '15 13 * * 3'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  trigger:
    runs-on: ubuntu-22.04

    steps:
    - name: Triggered CI-builds
      run: |
        echo "Triggered by workflow_run[in_progress]: '${{ github.ref_name }} CI-builds ${{ github.sha }}'"
    
    - name: Wait
      uses: lewagon/wait-on-check-action@v1.3.4
      with:
        ref: ${{ github.ref }}
        check-name: '${{ github.ref_name }} CI-builds ${{ github.sha }}'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 30

    - name: Triggered CI-dump
      run: |
        echo "Triggered by workflow_run[completed]: '${{ github.ref_name }} CI-dump ${{ github.sha }}'"
